/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain(String user) {
        initComponents();
        tfNamaKasir.setText(user);
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        dcTglKembali = new com.toedter.calendar.JDateChooser();
        dcTglPinjam = new com.toedter.calendar.JDateChooser();
        tfNoPol = new javax.swing.JTextField();
        tfNoStruk = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfNamaKasir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dcTglPinjam2 = new com.toedter.calendar.JDateChooser();
        dcTglKembali2 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);
        btnSearch.setBounds(860, 120, 110, 30);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(100, 470, 70, 23);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(180, 470, 80, 23);

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint);
        btnPrint.setBounds(270, 470, 80, 23);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("~~\"Anda Sukses Kami Senang\"~~");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(350, 40, 220, 30);

        jLabel1.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("FORM RENTAL SEPEDA MOTOR MAJU JAYA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(220, 0, 590, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 980, 90);

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbData);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(370, 160, 600, 330);
        jPanel1.add(dcTglKembali);
        dcTglKembali.setBounds(170, 380, 130, 30);
        jPanel1.add(dcTglPinjam);
        dcTglPinjam.setBounds(170, 340, 130, 30);
        jPanel1.add(tfNoPol);
        tfNoPol.setBounds(170, 300, 130, 30);

        tfNoStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoStrukActionPerformed(evt);
            }
        });
        jPanel1.add(tfNoStruk);
        tfNoStruk.setBounds(170, 260, 130, 30);

        tfAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlamatActionPerformed(evt);
            }
        });
        jPanel1.add(tfAlamat);
        tfAlamat.setBounds(170, 220, 130, 30);
        jPanel1.add(tfNama);
        tfNama.setBounds(170, 180, 130, 30);

        jLabel4.setText("NAMA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 190, 100, 14);

        jLabel5.setText("ALAMAT");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 230, 60, 14);

        jLabel6.setText("NO STRUK");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 270, 80, 14);

        jLabel7.setText("NO POL");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 310, 70, 14);

        jLabel8.setText("TANGGAL PINJAM");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 350, 110, 14);

        jLabel9.setText("TANGGAL KEMBALI");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 390, 110, 14);

        jLabel3.setText("ISI DATA PEMINJAM");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 120, 30);

        jLabel10.setText("NAMA KASIR");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 430, 100, 14);

        tfNamaKasir.setEditable(false);
        jPanel1.add(tfNamaKasir);
        tfNamaKasir.setBounds(170, 420, 130, 30);

        jLabel11.setText("TANGGAL PINJAM");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(370, 130, 110, 14);
        jPanel1.add(dcTglPinjam2);
        dcTglPinjam2.setBounds(470, 120, 130, 30);
        jPanel1.add(dcTglKembali2);
        dcTglKembali2.setBounds(710, 120, 130, 30);

        jLabel12.setText("TANGGAL KEMBALI");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(610, 130, 110, 14);

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(20, 470, 70, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 980, 520);

        setBounds(0, 0, 996, 561);
    }// </editor-fold>//GEN-END:initComponents

    private void tfAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlamatActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String kolom[] = {"No Struk","Nama","Alamat","No Polisi","Tanggal Peminjaman","Tanggal Kembali", "Total Harga", "Nama Kasir"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tglpinjam = dateFormat.format(dcTglPinjam2.getDate());
        String tglkembali = dateFormat.format(dcTglKembali2.getDate());
 
        String SQL = "SELECT * FROM tb_pinjam WHERE tgl_pinjam='"+tglpinjam+"' AND tgl_kembali='"+tglkembali+"'";
        ResultSet rs = Koneksi_DB.executeQuery(SQL);
        try {
            while(rs.next()){
                String no_struk = rs.getString(1);
                String nama = rs.getString(2);
                String alamat = rs.getString(3);
                String no_pol = rs.getString(4);
                String tgl_pinjam = rs.getString(5);
                String tgl_kembali = rs.getString(6);
                String harga = rs.getString(7);
                String nama_kasir = rs.getString(8);
                String data[] = {no_struk, nama, alamat, no_pol, tgl_pinjam, tgl_kembali, harga, nama_kasir};
                dtm.addRow(data);
            }
        } catch(SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbData.setModel(dtm);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tfNoStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoStrukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoStrukActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
      int baris = tbData.getSelectedRow();
      if(baris!= -1){
          tfNama.setText(tbData.getValueAt(baris, 1).toString());
          tfAlamat.setText(tbData.getValueAt(baris, 2).toString());
          tfNoStruk.setText(tbData.getValueAt(baris, 0).toString());
          tfNoPol.setText(tbData.getValueAt(baris, 3).toString());
          tfNamaKasir.setText(tbData.getValueAt(baris, 7).toString());
          
          
          SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            Date dateFormat1 = null;
            try {
            dateFormat = date.parse(tbData.getValueAt(baris, 4).toString());
            dateFormat1 = date.parse(tbData.getValueAt(baris, 5).toString());
            } catch (ParseException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }

            dcTglPinjam.setDate(dateFormat);
            dcTglKembali.setDate(dateFormat1);
            
      }        // TODO add your handling code here:
    }//GEN-LAST:event_tbDataMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
      tfNama.setText("");
      tfAlamat.setText("");
      tfNoStruk.setText("");
      tfNoPol.setText("");
      dcTglPinjam.setDate(null);
      dcTglKembali.setDate(null);
      tfNamaKasir.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris = tbData.getSelectedRow();
        if (baris != -1){
            String no_struk = tbData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_pinjam WHERE no_struk='"+no_struk+"'";
            int status = Koneksi_DB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else{
                JOptionPane.showMessageDialog(this, "Data Gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris terlebih dahulu sebelum menghapus", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
       MessageFormat header = new MessageFormat("SEPEDA MOTOR MAJU JAYA");
       MessageFormat footer = new MessageFormat("Page {0,number,integer}");
       
       try {
           tbData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
       } catch (java.awt.print.PrinterException e) {
           System.err.format("Cannot Print %s&n", e.getMessage());
       } 
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tglPinjam = dateFormat.format(dcTglPinjam.getDate());
        String tglKembali = dateFormat.format(dcTglKembali.getDate());
        int pinjam_h = dcTglPinjam.getDate().getDate();
        int kembali_h = dcTglKembali.getDate().getDate();
        int totalhari = kembali_h - pinjam_h;
        int total = totalhari * 20000;

                
        if ("".equals(tfNama.getText())||"".equals(tfAlamat.getText())||"".equals(tfNoStruk.getText())||"".equals(tfNoStruk.getText())||"".equals(tglPinjam)||"".equals(tglKembali)){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
         
         String SQL = "INSERT INTO tb_pinjam(no_struk, nama, alamat, no_pol, tgl_pinjam, tgl_kembali, harga) " + "VALUES('"+tfNoStruk.getText()+"','"+tfNama.getText()+"','"+tfAlamat.getText()+"','"+tfNoPol.getText()+"','"+tglPinjam+"','"+tglKembali+"','"+total+"')";
         int status = Koneksi_DB.execute(SQL);
         if (status == 1){
             JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
             selectData();
         }
         else{
             JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
         }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String user = null;
                new frmMain(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private com.toedter.calendar.JDateChooser dcTglKembali;
    private com.toedter.calendar.JDateChooser dcTglKembali2;
    private com.toedter.calendar.JDateChooser dcTglPinjam;
    private com.toedter.calendar.JDateChooser dcTglPinjam2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbData;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNamaKasir;
    private javax.swing.JTextField tfNoPol;
    private javax.swing.JTextField tfNoStruk;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"No Struk","Nama","Alamat","No Polisi","Tanggal Peminjaman","Tanggal Kembali", "Total Harga", "Nama Kasir"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_pinjam";
        ResultSet rs = Koneksi_DB.executeQuery(SQL);
        try {
            while(rs.next()){
                String no_struk = rs.getString(1);
                String nama = rs.getString(2);
                String alamat = rs.getString(3);
                String no_pol = rs.getString(4);
                String tgl_pinjam = rs.getString(5);
                String tgl_kembali = rs.getString(6);
                String harga = rs.getString(7);
                String nama_kasir = rs.getString(8);
                String data[] = {no_struk, nama, alamat, no_pol, tgl_pinjam, tgl_kembali, harga, nama_kasir};
                dtm.addRow(data);
            }
        } catch(SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbData.setModel(dtm);
    }
}
